#!/usr/bin/env bash

# Const vals
ANYRC_NAME='.anyrc'
ANYRCD_NAME='.anyrc.d'

ANYRC_CMD='anyrc'
ANYRC_CMD_SSH='sshrc'
ANYRC_CMD_DOCKER='dockerrc'
ANYRC_CMD_KUBECTLC='kubectlrc'
ANYRC_CMD_SU='surc'

ANYRC_CMDS=( \
  "${ANYRC_CMD_SSH}" \
  "${ANYRC_CMD_DOCKER}" \
  "${ANYRC_CMD_KUBECTL}" \
  "${ANYRC_CMD_SU}")



# Funcs
set_anyrc() {
  # .anyrc on local
  if [ -z "${ANYRC_ANYRC:+_}" ]; then
    if [ -f "${HOME}/${ANYRC_NAME}" ]; then # Home dir
      ANYRC_ANYRC="${HOME}/${ANYRC_NAME}"
    elif [ -f "$(pwd)/${ANYRC_NAME}" ]; then # Current dir
      ANYRC_ANYRC="$(pwd)/${ANYRC_NAME}"
    else
      echo >&2 "${ANYRC_NAME} not found"
      exit 1
    fi
  fi
}

set_anyrcd() {
  # .anyrc.d on local
  if [ -z "${ANYRC_ANYRCD:+_}" ]; then
    if [ -d "${HOME}/${ANYRCD_NAME}" ]; then # Home dir
      ANYRC_ANYRCD="${HOME}/${ANYRCD_NAME}"
    elif [ -d "$(pwd)/${ANYRCD_NAME}" ]; then # Current dir
      ANYRC_ANYRCD="$(pwd)/${ANYRCD_NAME}"
    else
      echo >&2 "${ANYRCD_NAME} not found"
      exit 1
    fi
  fi

  ANYRCD_BASE="${ANYRC_ANYRCD##*/}"
  ANYRCD_DIR="${ANYRC_ANYRCD%/*}"
}

abs_dirname() {
  local CWD="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local NAME="${path##*/}"
    path="$(readlink "${NAME}" || :)"
  done

  pwd -P
  cd "${CWD}"
}



# Main
init "$@" # (Inherit from *rc)

set_anyrc
set_anyrcd

mk_tmp_dir # (Inherit from *rc)

transfer # (Inherit from *rc)

connect # (Inherit from *rc)
