#!/usr/bin/env bash

export ANYRC_ENV='ssh'

init() {
  SSH_CMD="${ANYRC_SSH_CMD:-ssh}"
  SSH_OPTS=''
  while [[ -n "$1" ]]; do
    case "$1" in
      --ssh_cmd )
        SSH_CMD="$2"
        shift ;;
      -b | -c | -D | -E | -e | -F | -I | -i | -J | -L | -l | -m | -O | -o | -p | -Q | -R | -S | -W | -w )
        SSH_OPTS="${SSH_OPTS} $1 $2"; shift ;;
      -* )
        SSH_OPTS="${SSH_OPTS} $1" ;;
      * )
        if [ -z "${SSH_REMOTE:+_}" ]; then
          SSH_REMOTE="$1"
        fi; ;;
    esac
    shift
  done
  if [ -z "${SSH_REMOTE:+_}" ]; then
    ${SSH_CMD} "${SSH_OPTS[@]}"; exit 1;
  fi
}

mk_tmp_dir() {
  :
}

transfer() {
  :
}

connect() {
  local CMD_DIR="$(abs_dirname "$0")"
  ${SSH_CMD} -t "${SSH_REMOTE}" ${SSH_OPTS} "\
    base64_decode() { echo | base64 -d 2>/dev/null 1>/dev/null && base64 -d || base64 -D }

    export ANYRC_NAME=\"${ANYRC_NAME}\"
    export ANYRCD_NAME=\"${ANYRCD_NAME}\"
    export ANYRC_ROOT=\"\$(mktemp -d /tmp/anyrc.XXXXXX)\"
    export ANYRC_ANYRC=\"\${ANYRC_ROOT}/\${ANYRC_NAME}\"
    export ANYRC_ANYRCD=\"\${ANYRC_ROOT}/\${ANYRCD_NAME}\"
    export ANYRC_HOME=\"\${ANYRC_ANYRCD}\"

    export PATH=\"\${ANYRC_ROOT}:\${PATH}\"

    trap \"rm -rf \${ANYRC_ROOT}; exit\" 0
    mkdir -p \${ANYRC_ANYRCD}

    echo '$(base64 < "${ANYRC_ANYRC}")' | tr -s ' ' '\n' | base64_decode > \${ANYRC_ANYRC}
    echo '$(tar czf - -h -C "${CMD_DIR}" "${ANYRC_CMD}" "${ANYRC_CMDS[@]}" | base64)' | tr -s ' ' $'\n' | base64_decode | tar mxzf - -C \"\${ANYRC_ROOT}\"
    echo '$(tar czf - -h -C "${ANYRCD_DIR}" "${ANYRCD_BASE}" | base64)' | tr -s ' ' '\n' | base64_decode | tar mxzf - -C \"\${ANYRC_ROOT}\"

    if [ \"\${SHELL##*/}\" = 'bash' ]; then
      [[ -e \${ANYRC_HOME}/.bashrc ]] && bash --rcfile \${ANYRC_HOME}/.bashrc || bash --rcfile \${ANYRC_ANYRC}
    elif [ \"\${SHELL##*/}\" = 'zsh' ]; then
      [[ -e \${ANYRC_HOME}/.zshrc ]] && ZDOTDIR=\"\${ANYRC_HOME}\" zsh || ln -sf \${ANYRC_ANYRC} \${ANYRC_HOME}/.zshrc && ZDOTDIR=\"\${ANYRC_HOME}\" zsh
    else
      \${SHELL};
    fi"
}

source anyrc
