#!/usr/bin/env bash

ANYRC_ENV='su'

init() {
  SU_OPTS=''
  while [[ -n "$1" ]]; do
    case $1 in
      -* )
        SU_OPTS="${SU_OPTS} $1" ;;
      * )
        if [ -z "${SU_USER:+_}" ]; then
         SU_USER="$1"
        fi; ;;
    esac
    shift
  done
  if [ -z "${SU_USER:+_}" ]; then
    exit 1
  fi
}

mk_tmp_dir() {
  TMP_DIR="$(mktemp -d /tmp/anyrc.XXXXXX)"
}

transfer() {
  cp "${ANYRC_ANYRC}" "${TMP_DIR}/${ANYRC_NAME}"
  cp -r "${ANYRC_ANYRCD}" "${TMP_DIR}/${ANYRCD_NAME}"

  # Transfer *rc
  local CMD_DIR="$(abs_dirname $0)"
  for cmd in "${ANYRC_CMD}" "${ANYRC_CMDS[@]}"; do
    if [ -f "${CMD_DIR}/${cmd}" ]; then
      cp "${CMD_DIR}/${cmd}" "${TMP_DIR}/${cmd}"
    fi
  done

  chmod -R 777 "${TMP_DIR}"
}

connect() {
  sudo -s -u "${SU_USER}" ${SU_OPTS} bash -c "\
      export ANYRC_NAME=\"${ANYRC_NAME}\" && \
      export ANYRCD_NAME=\"${ANYRCD_NAME}\" && \
      export ANYRC_ROOT=\"${TMP_DIR}\" && \
      export ANYRC_ANYRC=\"\${ANYRC_ROOT}/\${ANYRC_NAME}\" && \
      export ANYRC_ANYRCD=\"\${ANYRC_ROOT}/\${ANYRCD_NAME}\" && \
      export ANYRC_HOME=\"\${ANYRC_ANYRCD}\" && \
      export PATH=\"\${ANYRC_ROOT}:\${PATH}\" && \
      trap \"rm -rf \${ANYRC_ROOT}/*; exit\" 0 && \
      mkdir -p \${ANYRC_ANYRCD} && \
      source \${ANYRC_ANYRC}
      if [ \"\${SHELL##*/}\" = 'bash' ]; then
        bash --rcfile \${ANYRC_ANYRC};
      else
        \${SHELL};
      fi"
  rm -rf "${TMP_DIR}" # FIXME
}

source anyrc
